services:
  asterisk:
    build:
      context: .
      dockerfile: ./Dockerfile.asterisk
    container_name: asterisk
    ports:
      - "5060:5060/udp"
      - "5060:5060/tcp"
      - "5038:5038"
      - "8088:8088"
      - "10000-10050:10000-10050/udp"
    networks:
      - asterisk-net
    depends_on:
      - audioserver

  audioserver:
    build:
      context: .
      dockerfile: ./Dockerfile.audioserver
    container_name: audioserver
    networks:
      - asterisk-net
    expose:
      - "8080"  # только для внутренней сети

networks:
  asterisk-net:
    driver: bridge
