services:
  asterisk:
    build:
      context: .
      dockerfile: ./Dockerfile.asterisk
    container_name: asterisk
    ports:
      - "5060:5060/udp"
      - "5060:5060/tcp"
      - "5038:5038"
      - "8088:8088"
      - "10000-10050:10000-10050/udp"
    expose:
      - "8088"
    networks:
      - asterisk-net

  # rtp_listener:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile.rtp_listener
  #   container_name: rtp_listener
  #   networks:
  #     - asterisk-net
  #   expose:
  #     - "10000"

  ari_handler:
    build:
      context: .
      dockerfile: ./Dockerfile.ari_handler
    container_name: ari_handler
    networks:
      - asterisk-net
    depends_on:
      - asterisk
    ports:
      - "8765:8765"
    # restart: always

networks:
  asterisk-net:
    driver: bridge
