services:
  asterisk:
    build:
      context: .
      dockerfile: ./Dockerfile.asterisk
    container_name: asterisk
    ports:
      - "5060:5060/udp"
      - "5060:5060/tcp"
      - "5038:5038"
      - "8088:8088"
      - "10000-10050:10000-10050/udp"
    expose:
      - "8088"
    networks:
      - voice-net

  ari-handler:
    build:
      context: .
      dockerfile: ./Dockerfile.ari-handler
    container_name: ari-handler
    networks:
      - voice-net
    depends_on:
      - asterisk
    ports:
      - "8765:8765"
    restart: always

networks:
  voice-net:
    driver: bridge
